name: Master branch scanning

on:
  push:
    branches:
      - master

jobs:
  sonar-qube-scan:
    name: sonar-qube-scan
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 24.x ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create .env
        shell: bash
        env:
          ENVIRONMENT_VARIABLES: ${{ secrets.ENV }}
        run: |
          umask 077
          printf '%s\n' "$DOTENV_CONTENT" > .env
          chmod 600 .env

      - name: Load env variables
        shell: bash
        run: |
          sed -E '/^\s*($|#)/d' .env >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Coverage tests
        run: npm run test:cov

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9 # v7.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
