name: Master branch scanning

on:
  push:
    branches:
      - master

jobs:
  sonar-qube-scan:
    name: sonar-qube-scan
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 24.x ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v6.1.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create .env
        shell: bash
        run: |
          printf '%s\n' "${{ secrets.ENV }}" > .env

      - name: Load env variables
        shell: bash
        run: |
          sed -E '/^\s*($|#)/d' .env >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Coverage tests
        run: npm run test:cov

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
